# Generated by Django 4.2.4 on 2023-09-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
