# Generated by Django 4.2.4 on 2023-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_orderitem_addcart_order_cartitems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_confirmation',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
