# Generated by Django 4.2.6 on 2023-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_orderitem_order_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
