# Generated by Django 4.2.4 on 2023-09-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_addcart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='AddCart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
