# Generated by Django 4.2.5 on 2023-10-24 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_reviewrating_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shippings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipname', models.CharField(max_length=100)),
                ('shipaddress', models.TextField(blank=True, null=True)),
                ('shipcity', models.TextField(blank=True, null=True)),
                ('shippingpincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
