# Generated by Django 4.2.5 on 2023-10-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_shippings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippings',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order'),
        ),
    ]
