# Generated by Django 4.2.4 on 2023-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_customuser_email_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin'), ('delivery_agent', 'Delivery Agent')], default='customer', max_length=15, null=True),
        ),
    ]
