# Generated by Django 4.2.5 on 2024-01-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_deliveryagent_assigned_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='assigned_seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
