# Generated by Django 4.2.5 on 2024-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_route_deliveryagent_assigned_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='pincode',
            new_name='Route_number',
        ),
        migrations.AddField(
            model_name='route',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
