# Generated by Django 4.2.5 on 2024-01-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_pincode_route_route_number_route_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='assigned_route',
        ),
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
