# Generated by Django 4.2.5 on 2024-01-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_deliveryagent_assigned_route_seller_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('delivery_agent_assignment', 'Delivery Agent Assignment'), ('other_notification_type', 'Other Notification Type')], max_length=50, null=True),
        ),
    ]
