# Generated by Django 4.2.5 on 2024-01-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_seller_nearby_delivery_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
