# Generated by Django 4.2.5 on 2024-01-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_customer_latitude_customer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.deliveryagent'),
        ),
    ]
