# Generated by Django 4.2.5 on 2024-01-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_deliveryagent_is_available_order_delivery_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_agent',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.deliveryagent'),
        ),
    ]
