# Generated by Django 4.2.5 on 2024-01-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_orderitem_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_status',
        ),
    ]
