# Generated by Django 4.2.5 on 2024-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_order_delivery_status_remove_order_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_transit', 'in_transit'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
