# Generated by Django 4.2.5 on 2024-02-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_orderitem_delivered_orderitem_order_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processed', 'Processed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
