# Generated by Django 4.2.5 on 2024-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_qualitycheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processed', 'Processed'), ('qualitycheck', 'QualityCheck'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
