# Generated by Django 4.2.5 on 2024-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_orderitem_order_qualitycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
