# Generated by Django 4.2.5 on 2024-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_orderitem_order_confirmed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_qualitycheck_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_dispatched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
