# Generated by Django 4.2.5 on 2024-02-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_orderitem_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='3d_models'),
        ),
    ]
